version: '3'

services:
    coturn:
        container_name: coturn
        image: coturn/coturn:4.5.2
        restart: always
        network_mode: host
        volumes:
            - ./certbot/etc/letsencrypt:/etc/letsencrypt
        command:
            - --cert=/etc/letsencrypt/live/${COTURN_DOMAIN_NAME}/cert.pem
            - --pkey=/etc/letsencrypt/live/${COTURN_DOMAIN_NAME}/privkey.pem
            - --realm=${COTURN_DOMAIN_NAME}
            - --fingerprint
            - --listening-ip=0.0.0.0
            - --external-ip=$$(detect-external-ip)
            - --listening-port=443
            - --tls-listening-port=443
            - --min-port=${MIN_PORT:-40000}
            - --max-port=${MAX_PORT:-65535}
            - --log-file=stdout
            - --verbose
            - --user=${TURN_USERNAME}:${TURN_PASSWORD}
            - --lt-cred-mech
        logging:
            options:
                max-size: "${DOCKER_LOGS_MAX_SIZE:-100M}"

    # Autorenew certbot
    certbot:
        build: ./docker/certbot-coturn
        image: certbot-coturn
        container_name: certbot-coturn
        restart: always
        ports:
            # This port is necessary to verify domain with letsencrypt
            - 80:80
        environment:
            - CRONTIME=12h
            - COTURN_CONTAINER_NAME=coturn
        volumes:
            - ./certbot/etc/letsencrypt:/etc/letsencrypt
            - ./certbot/var/lib/letsencrypt:/var/lib/letsencrypt
            - ./certbot/var/www/certbot:/var/www/certbot
            - /var/run/docker.sock:/var/run/docker.sock
        command:
            - certonly
            - --non-interactive
            - --standalone
            - --preferred-challenges=http
            - --email=${LETSENCRYPT_EMAIL}
            - --agree-tos
            - --domain=${COTURN_DOMAIN_NAME}
        logging:
            options:
                max-size: "${DOCKER_LOGS_MAX_SIZE:-100M}"
